### PR TITLE
Grenades

### PR DESCRIPTION
**Pull request by Mikolaj**
Let's brainstorm about this mock-up of specialised explosive projectiles, which resulted from @Peritract 's game flavour prose PR #118 and from ideas of @tuturto from his game [Space Privateers](https://github.com/tuturto/space-privateers). More discussion is in the comments inside the code below. In short, it's possible to define focused explosions that not only expand outward, but harm the actor that is at their centre as well. Consequently, we can have grenades, mines, etc, and not just exploding potions as we had before (that never explode on direct hit). The questions is, how best to present, organise and balance such items so that they match the theme and are fun to play with.

Explosives in action, as defined in this PR, that is on branch `grenades` (click to enlarge):
allureofthestars com firecrackers

### CODE REVIEW

**Comment by Mikolaj** [comment]
Thank you very much for your comments. So, out of interest, say, in Space Privateers, would you rather have
1. many kinds of grenades (can still be rare) that are so similar that they are identified only when they explode (and then you recognize that kind of grenade always)
2. just a couple of kinds of grenades, so distinct regarding looks and real-world rationale that their identity and so also the explosion type (and strength, radius, etc.) is known as soon as you spot them?
3. grenades that all look the same, but have different explosions and you can't ever tell from the look of the grenade (that would be the description, while the implementation would just be a single grenade kind with random explosion effect)?

Regardings the barrel, yeah, would be fun. :) Currently it's only possible to make the barrels so heavy that when thrown they just drop down on an adjacent tile, harming the throwing actor when they explode. The item moving kill (including pickup) is not yet checked vs weight, but it's not a bad idea --- then higher levels of that skill would be more useful and at some point we could start treating the skill seriously (temporarily or permanently increasing of decreasing it via items/organs/levelups). Feel free to file an issue about that.

Regardless, there is currently no way to activate an item that lies inertly on the floor, except for when you stand on the same position. However, when we embed the barrel inside a tile, say inside a treasure cache, or even "inside" a floor tile (it then can't be picked up), you can activate it when you stand on an adjacent tile (loot the cache, open trapped door, prod the barrel on the floor with a stick). And then it can explode, every time, or as one of possible effects, and it can then vanish or not, cause the door to open, etc. This is already quite comprehensively implemented on master branch (or even in the last published version).

So I guess the easiest way of shooting a barrel would be to implement activating embedded items by throwing other items at them. That's actually not hard to do. Already on the master branch, when a hero is pushed and he collides with a door, he opens the door (or suffers some damage, if his door opening skill is too low). More generally, when he collides with a solid tile, he triggers it (alters and/or activates embedded items). The code ensures that inanimate projectiles can't do that, but it's easy to add an exception and so allow some projectiles to activate some embedded items when they collide with them. E.g., we could allow any projectiles that have `Burn` effect to trigger any embedded item that has `OnSmash (Explode "foo")` effect or that has `Fragile` feature. That could also benefit from a github issue to brainstorm before implementation.

**Comment by tuturto** [comment]
In space privateers, I would rather have just few different kinds of grenades that are all distinct and easy to tell apart (ie. identified as soon as you get one). This limits trial and error, and gives player chance to plan their actions tactically. I probably would go as far as having each grenade type to be very distinct:
 - fragmentation grenade throws around shards that cause damage
 - concussion grenade creates shockwave that disorients anyone caught in the blast and maybe make them drop their weapon
 - flashbang causes lots of sparkling effects that don't cause damage, but make targets to miss their turn (or delay it)
 - flame grenade soaks area with gasoline, causing fire damage that burns for a while
 - delay fuse cluster that spawns multiple shell from initial explosion that explode after a while, ie. one explosion in the middle and then several ones randomly around it after considerable delay.
and so on. In my opinion, this is more intersted than having several different kinds of grenades that differ from each other by just the strength of the effect.

**Comment by Mikolaj** [comment]
Wow, thank you, these are interesting ideas. I my games role 1. is filled with potions and flasks, role 3. by a couple of potions with random effects, so I guess I will go with 2. as well. I will try to implement a couple of your suggestions and then ponder how to name and describe them to keep the player informed and immersed.

Putting terrain on temporary fire is no possible yet, but I'm getting there slowly. Similarly, you old idea of a flame thrower that lights up actors standing behind other actors, if only within the cone of effect. This can be implemented by putting a conical shape of terrain on fire for a moment or by projectiles that pierce actors and so reach actors behind them. Both of these features are now probably within reach, without upholding the whole engine. I will keep you posted.

**Comment by Mikolaj** [comment]
@tuturto: OK, so I took your ideas, googled details and implemented a couple of distinct projectiles. Thanks again. The "delay fuse cluster" would require a tiny change to the engine to permit non-moving projectiles to model the ejected charges with delayed explosion. The non-moving projectile is a compromise --- you can shoot through it, displace it, hit it, if barehanded then steal the charge (which stops its clock, unless it's put into the equipment store), but you can't stand over it, move across it, pick it up and you can't shoot at it. We'd need to brainstorm to fix the compromise (e.g., with some effort one would be able to shoot at it, at least with explosive projectiles, and so trigger the explosion).

@Peritract: If you'd like to look at the world-building, tone, mood, backstory, prose aspects of the new items, I'm sure you'd bring them to life with a kick, as you did before. I will keep this PR open for a week or two more and then merge the results and port them to Allure.

**Comment by Mikolaj** [comment]
The gif is a showcase of shooting down explosives (click to enlarge, I chose the smallest font, but it still doesn't fit :< ). A couple were shot down close enough to enemies to harm them. Others exploded closer to our party members and took out of the air projectiles that would otherwise harm them.

allureofthestars com shooting down explosives

This is a semi-automatic stealthy speedrun of the escape scenario. The enemy gang has a huge numerical and equipment superiority. Our team loots the area on auto-pilot until the first foe is spotted. Then they scout out enemy positions. Then hero 1 draws enemies and unfortunately enemy fire as well, which is when he valiantly shoots down explosives to avoid the worst damage. Then heroine 2 sneaks behind enemy lines to reach the remaining treasure. That accomplished, the captain signals retreat and leaves for the next area (the zoo).

The work on explosives is complete. Only the prose remains to be written and not only for explosives, but for many other entities that I previously missed as needing description. I'm loath to write this myself, since it would disrupt the unmatched corpus of @Peritract's prose.

**Comment by Mikolaj** [comment]
I've tweeted the second gif at https://twitter.com/AllureRoguelike/status/964661923550810112

Thank you very much for your feedback. Merging.

**Pull request merged**
