### PR TITLE
update first attempt

### PR DESCRIPTION
**Pull request by Mistuke**

### CODE REVIEW

**Comment by Mistuke** [comment]
whoops, wrong repo

**Comment by Mistuke** [comment]
Oh I'm not done with it yet, need to fix the v2 builds and add the installer deploy back in :)

**Comment by Mikolaj** [comment]
BTW, here's another variant, much simpler, because the appveyor matrix somehow breaks the syntax, but this one doesn't do many tests, but just a single run: https://github.com/AllureOfTheStars/Allure/blob/master/appveyor.yml

**Comment by Mistuke** [comment]
Yeah that does look pretty much the same. The same approach should work for it as well. the reason `refreshenv` didn't work for you before btw was because of the manual path updates later. I'll try to finish the changes tomorrow.

**Comment by Mikolaj** [comment]
BTW, one more problem I have with my crummy appveyor scripts is that error messages and stack traces are not shown, despite my attempts (on travis something like that works). See the end of https://ci.appveyor.com/project/Mikolaj/lambdahack/builds/28095334/job/21v8he80rwm9bnd5

**Comment by Mikolaj** [comment]
Thank you. :) No hurry at all.

**Comment by Mistuke** [comment]
I haven't forgotten about this, had some release blocking things to fix for GHC and I'm trying to find a workaround for https://github.com/haskell/cabal/issues/6304 and will finish it off. I have some big work deadlines next week but after that I should have free time to finish it!

**Comment by Mikolaj** [comment]
Heh, and I thought I'm the last weird one that cares about what he promised to people he doesn't report to. Very appreciated and absolutely no hurry. :)

**Comment by Mikolaj** [comment]
Congratulations on the WinIO release!

Just writing that I cleaned up the Makefiles (mainly) so that the old v1- scripts are still at `make build-binary-common`, but the v2- ones, for Windows, are at `make build-binary-windows`. Changing one doesn't break the other now, so future rebasing should be easier (not the first one, though). The v2- Windws scripts are analogous to Linux scripts, so I hope they can be made to work in this form, without any extra significant hacks for Windows.

I only slightly tweaked appveyor.yml.  I think we don't need to add `source-repository-package` to `cabal.project`, because building sdl from source was a leftover from when Hackage version lagged behind the source and also, with v2-, the special flag should be automatically added from `cabal.project`, so doesn't need to be build via a separate commandline cabal call at all.

**Comment by Mistuke** [comment]
Thanks! We're also officially dropping ghc 32-bits support. Sadly it's too much to maintain and we've been hitting the limits of the linker etc with it often..

**Comment by Mikolaj** [comment]
Yes, I know. I'm sure that's for the best, but I will have to upgrade Windows at some point due to that. Oh, well. Thank you for all the help and your splendid efforts in this area.

**Comment by Mikolaj** [comment]
I've finally upgraded from Vista to Windows 7, but I stayed with 32bits, so I'm still behind the curve, it seems. ;)

When I need to use GHC newer than 8.6.5, I will switch to solely 64bits and abandon all players (no clue if there are any) that use 32bit systems. Then I will also switch to a standard appveyor script and use bits from your work here if still needed.

Thank you for your help. Closing.

**Pull request closed without merging**
